version: '{build}'
pull_requests:
  do_not_increment_build_number: true
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
build_script:
- sh: ./build.sh
test: off
artifacts:
- path: '**\artifacts\*.nupkg'
  name: NuGet
